/**
 * lib/rare-earth-geo-data.ts
 * @why Rare earth element geographic data — mine locations, reserve estimates, country production
 * @consts RARE_EARTH_GEO_BOUNDARIES, RARE_EARTH_CONFLICT_SITES
 * @connections composables/useRareEarthLayers.ts
 */
export const RARE_EARTH_GEO_BOUNDARIES: GeoJSON.FeatureCollection = {
  type: 'FeatureCollection',
  features: [
    { type: 'Feature', properties: { name: 'São Francisco Basin', type: 'basin' }, geometry: { type: 'Polygon', coordinates: [[[-47, -12], [-44, -12], [-42, -13], [-40, -14], [-39, -15.5], [-39.5, -17], [-40, -18.5], [-42, -19.5], [-44, -20], [-46, -20.5], [-48, -19], [-49, -17], [-48.5, -15], [-47.5, -13.5], [-47, -12]]] } },
    { type: 'Feature', properties: { name: 'Paranaíba Basin', type: 'basin' }, geometry: { type: 'Polygon', coordinates: [[[-49, -17], [-47.5, -17.5], [-46.5, -18.5], [-46, -19.5], [-47, -20.5], [-48.5, -20.5], [-50, -20], [-51.5, -19], [-51, -17.5], [-50, -17], [-49, -17]]] } },
    { type: 'Feature', properties: { name: 'Jequitinhonha Basin', type: 'basin' }, geometry: { type: 'Polygon', coordinates: [[[-42, -15.5], [-40.5, -15.5], [-39.5, -16], [-39.5, -17.5], [-40.5, -18], [-42, -17.5], [-43, -16.5], [-42, -15.5]]] } },
    { type: 'Feature', properties: { name: 'Bambuí Aquifer', type: 'aquifer' }, geometry: { type: 'Polygon', coordinates: [[[-49, -15], [-47, -15], [-45, -16], [-44, -18], [-44.5, -20], [-46, -21], [-48.5, -21], [-50, -20], [-51, -18], [-50.5, -16], [-49, -15]]] } },
    { type: 'Feature', properties: { name: 'Urucuia Aquifer', type: 'aquifer' }, geometry: { type: 'Polygon', coordinates: [[[-46, -13], [-43.5, -13], [-42, -14.5], [-42.5, -16.5], [-44, -17.5], [-46, -17.5], [-47, -16], [-46, -13]]] } },
    // INB Caldas — zona de amortecimento (3 km ring around the real
    // ANM claim 180.266/1977; generated by scripts/generate-inb-apa-overlays.py).
    // Replaces the former oversized 'INB Caldas Nuclear' box that
    // duplicated the claim polygon and covered most of the Planalto.
    { type: 'Feature', properties: { name: 'INB Caldas \u00b7 Zona de Amortecimento (3 km)', type: 'nuclear_buffer' }, geometry: { type: 'Polygon', coordinates: [[[-46.56575,-22.012558],[-46.451012,-22.013613],[-46.449887,-21.905014],[-46.545421,-21.904145],[-46.545517,-21.913173],[-46.557617,-21.913061],[-46.557804,-21.930673],[-46.564869,-21.930608],[-46.56575,-22.012558]],[[-46.53607,-21.957854],[-46.529002,-21.957919],[-46.528815,-21.940309],[-46.516715,-21.940421],[-46.516619,-21.931388],[-46.479255,-21.931728],[-46.479821,-21.986367],[-46.536371,-21.985847],[-46.53607,-21.957854]]] } },
    // NOTE: the former 'Poços de Caldas Conflict' polygon was removed — it
    // duplicated the mining-claim + circle overlays already centered on the
    // plateau and added no independent information.
  ],
}

export const RARE_EARTH_CONFLICT_SITES: GeoJSON.FeatureCollection = {
  type: 'FeatureCollection',
  features: [
    // NOTE: the former 'Poços de Caldas' CONFLICT site marker was removed —
    // redundant with the claim/polygon/circle overlays centered on the plateau.
    { type: 'Feature', properties: { name: 'Araxá', danger: 8.5, tag: 'REE + CBMM' }, geometry: { type: 'Point', coordinates: [-46.94, -19.59] } },
    { type: 'Feature', properties: { name: 'Jequié Corridor', danger: 7.5, tag: 'SPECULATION' }, geometry: { type: 'Point', coordinates: [-40.48, -13.85] } },
    { type: 'Feature', properties: { name: 'Serra Verde', danger: 9, tag: 'US DFC $565M' }, geometry: { type: 'Point', coordinates: [-48.1, -14.25] } },
    { type: 'Feature', properties: { name: 'Aclara Carina', danger: 7, tag: 'State Dept $5M' }, geometry: { type: 'Point', coordinates: [-49.1, -16.7] } },
    { type: 'Feature', properties: { name: 'Bambuí Aquifer', danger: 9, tag: 'CONTAMINATION' }, geometry: { type: 'Point', coordinates: [-47, -17.5] } },
  ],
}
